DROP TABLE IF EXISTS UTILISATEUR CASCADE; --

CREATE TABLE UTILISATEUR (
	ID VARCHAR(10) PRIMARY KEY,
	login VARCHAR(20) NOT NULL,
	motDePasse VARCHAR(20) NOT NULL,
	nom VARCHAR(30) NOT NULL,
	prenom VARCHAR(30) NOT NULL,
	societe VARCHAR(30),
	telephone VARCHAR(30),
	dateDeCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --TIMESTAMP est le format qui contient la date et l'heure
	statusActive BOOLEAN DEFAULT TRUE,
	statusAdmin BOOLEAN DEFAULT FALSE,
);

