DROP TABLE IF EXISTS 'UTILISATEUR' CASCADE; 

CREATE TABLE `sr03p037`.'UTILISATEUR' (
	'ID' VARCHAR(10) PRIMARY KEY AUTO_INCREMENT,
	'login' VARCHAR(20) NOT NULL,
	'motDePasse' VARCHAR(20) NOT NULL,
	'nom' VARCHAR(30) NOT NULL,
	'prenom' VARCHAR(30) NOT NULL,
	'societe' VARCHAR(30),
	'telephone' VARCHAR(30),
	'email' VARCHAR(150) NOT NULL,
	'dateDeCreation' TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	'statusActif' BOOLEAN DEFAULT TRUE,
	'statusAdmin' BOOLEAN DEFAULT FALSE,
	CHECK (email NOT REGEXP '^[a-zA-Z0-9][a-zA-Z0-9._-]*@[a-zA-Z0-9][a-zA-Z0-9._-]*\\.[a-zA-Z]{2,4}$')
);

CREATE TABLE `sr03p037`.`QUESTION` ( 
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	`libelle` VARCHAR(150) NOT NULL 
);
CREATE TABLE `sr03p037`.`QUESTIONNAIRE` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	`nom` VARCHAR(30) NOT NULL
);






